### ISSUE TITLE
⚙ [Support Request] GitHub Actions from macOS

### ISSUE THREAD

**Issue by schnek** [AscEmu/AscEmu#1012]
**Description**: ran into a problem ( linking mysql problem) writing a build script for macos. maybe someone will fix faster. 
```
name: AscEmu macOS 

on: [push]

env:
  BUILD_TYPE: Release
  REPO_DIR : ${{github.workspace}}
  BUILD_DIR: ${{github.workspace}}/bin/builddir

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{env.REPO_DIR}}
      - name: Install dependencies
        run: |
          brew update
          brew install mysql@5.7
          brew install openssl@1.1
          echo "OPENSSL_ROOT_DIR=$(brew --prefix --installed openssl@1.1)" >> $GITHUB_ENV
      - name: Build
        env:
          MAKEFLAGS: "-j8"
        run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}


```
log github
```

-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected Release configuration
-- Found OpenSSL: /usr/local/opt/openssl@1.1/lib/libcrypto.dylib (found version "1.1.1n")  
-- Detected system: Darwin  (x86_64)
-- Applying settings for macOS system
-- Found ZLIB: /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/libz.tbd (found version "1.2.11") 
-- Found PCRE: /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/libpcre.tbd  
-- Found OpenSSL library: /usr/local/opt/openssl@1.1/lib/libssl.dylib;/usr/local/opt/openssl@1.1/lib/libcrypto.dylib
-- Found OpenSSL headers: /usr/local/opt/openssl@1.1/include
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
CMake Error at cmake/Modules/FindMySQL.cmake:80 (message):
  Could not find the MySQL libraries! Please install the development
  libraries and headers
-- Configuring incomplete, errors occurred!
Call Stack (most recent call first):
See also "/Users/runner/work/AscEmu/AscEmu/CMakeFiles/CMakeOutput.log".
  cmake/Systems/Apple.cmake:14 (find_package)
See also "/Users/runner/work/AscEmu/AscEmu/CMakeFiles/CMakeError.log".
  cmake/CheckSystem.cmake:26 (include)
  CMakeLists.txt:[20](https://github.com/schnek/AscEmu/runs/6128966556?check_suite_focus=true#step:4:20) (include)

```
